// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: posts_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostTag = `-- name: CreatePostTag :one
INSERT INTO posts_tags (
  post_id
 ,tag_id
) VALUES (
  $1,$2
) RETURNING id, post_id, tag_id, created_at, updated_at
`

type CreatePostTagParams struct {
	PostID uuid.UUID `json:"post_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) CreatePostTag(ctx context.Context, arg CreatePostTagParams) (PostsTag, error) {
	row := q.db.QueryRow(ctx, createPostTag, arg.PostID, arg.TagID)
	var i PostsTag
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostTag = `-- name: DeletePostTag :exec
DELETE FROM posts_tags
WHERE id = $1
`

func (q *Queries) DeletePostTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostTag, id)
	return err
}
