// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostTag(ctx context.Context, arg CreatePostTagParams) (PostsTag, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeletePostTag(ctx context.Context, id uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetPostByCategoryPrivate(ctx context.Context, id uuid.UUID) ([]GetPostByCategoryPrivateRow, error)
	GetPostByCategoryPublic(ctx context.Context, id uuid.UUID) ([]GetPostByCategoryPublicRow, error)
	GetPostByIdPrivate(ctx context.Context, id uuid.UUID) (GetPostByIdPrivateRow, error)
	GetPostByIdPublic(ctx context.Context, id uuid.UUID) (GetPostByIdPublicRow, error)
	GetPostByTagPrivate(ctx context.Context, id uuid.UUID) ([]GetPostByTagPrivateRow, error)
	GetPostByTagPublic(ctx context.Context, id uuid.UUID) ([]GetPostByTagPublicRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTag(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListPostsPrivate(ctx context.Context) ([]ListPostsPrivateRow, error)
	ListPostsPublic(ctx context.Context) ([]ListPostsPublicRow, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
