// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRole(ctx context.Context, name string) (Role, error)
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
